driver password recovery
V-inTim/TaxiUNN pull request #15
Opened 2024-12-15 12:45 UTC by ErikBjornson

2024-12-15 12:59 UTC, ErikBjornson commented
@V-inTim @Stepa123de сделайте, пожалуйста, review

2024-12-17 19:11 UTC, Stepa123de commented on taxiunn/driver_auth/views.py
> +                return Response(
в секции `try` не должен находиться код, который не вызывает ошибку

2024-12-17 19:27 UTC, Stepa123de commented on taxiunn/driver_auth/views.py
> +        if serializer.is_valid():
можно сразу проверить `if not serializer.is_valid():`
 и код будет на строчку  ниже

2024-12-17 19:30 UTC, Stepa123de commented on taxiunn/driver_auth/views.py
> +        )
```suggestion
        if not serializer.is_valid():
            return Response(
                serializer.errors,
                status=status.HTTP_400_BAD_REQUEST,
            )

        email = serializer.validated_data['email']
        verify_code = serializer.validated_data['verification_code']

        if not PasswordRecoveryCache.verify(email=email, code=verify_code):
            return Response(
                {
                    'verification_code':
                        ['The verification code is not active.'],
                },
                status=status.HTTP_400_BAD_REQUEST,
            )
    
        return Response(
            {'message': ['Verification was successful.']},
            status=status.HTTP_200_OK,
        )
```

2024-12-17 19:30 UTC, Stepa123de commented on taxiunn/driver_auth/views.py
> +        if serializer.is_valid():
аналогично предыдущему

2024-12-17 19:51 UTC, Stepa123de commented on taxiunn/driver_auth/models.py
> +            raise TypeError('Driver must have a name!')
прошу обратить внимание на `class Driver(AbstractBaseUser):`
`null=False` гарантирует что поле не может быть null
`blank=False` гарантирует что поле обязательное для заполнения 
к примеру 
```py
class Client(AbstractBaseUser):
    email = models.EmailField(unique=True, null=False, blank=False)
    full_name = models.CharField(max_length=255, null=False, blank=False)
```
тогда проверки is None не понадобятся понадобятся
также в моделе можно навесить проверку на отдельные поля
```py
class Client(AbstractBaseUser):
    ...
     def clean(self):
        super().clean()
        if len(self.full_name) < 5:
            raise ValidationError('Full name must be at least 5 characters 
```
### ДОП задание на оценку первосходно
создать базовый класс `TaxiUser` ниже приведены одинаковые поля
```py
class Client(AbstractBaseUser):
    """Класс клиента."""

    email = models.EmailField(db_index=True, unique=True)
    full_name = models.CharField(null=True, default=None)

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    ...
    
    USERNAME_FIELD = 'email'

    def __str__(self):
        return self.email

    def make_superuser(self):
        self.is_staff = True
        self.is_superuser = True
class Driver(AbstractBaseUser):
    """Класс водителя."""

    email = models.EmailField(db_index=True, unique=True)
    full_name = models.CharField(null=True, default=None)

    is_active = models.BooleanField(default=True)
    is_stuff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
        
    ...
    
    USERNAME_FIELD = 'email'

    def __str__(self):
        return self.email

    def make_superuser(self):
        self.is_staff = True
        self.is_superuser = True
```

2024-12-17 19:52 UTC, Stepa123de commented on taxiunn/driver_auth/models.py
> +            raise TypeError('Driver must have a name!')
### P.S. c моделями можно проделать такую-же магию ООП

2024-12-17 19:55 UTC, Stepa123de requested changes
Оставил Ревью

2024-12-24 07:20 UTC, merged